# load libraries
library(shiny)
library(shinythemes)
library(shinyjs)
library(shinyBS)
library(SmartPhos)
library(shinycssloaders)
library(shinyWidgets)
library(parallel)
library(optimParallel)
library(DT)
library(tools)
library(stats)
library(plotly)
library(ggbeeswarm)
library(pheatmap)
library(grid)
library(MultiAssayExperiment)
# library(MatrixQCvis)
library(XML)
library(DEP)
library(missForest)
library(limma)
#library(OmnipathR)
library(decoupleR)
library(proDA)
library(piano)
library(tidyverse) #tidyverse should normally always be the last